import type { AppNotification } from "@/lib/notifications/types"

export const notificationMockData: AppNotification[] = [
  {
    id: "notification-mention-t001",
    kind: "mention",
    source: "Sarah Chen",
    action: "mentioned you in",
    objectLabel: "Ticket #-001",
    detail: "Can you confirm the onboarding handoff?",
    timestampLabel: "5m",
    dateGroup: "Today",
    destination: "/tickets/t-001",
    isRead: false,
  },
  {
    id: "notification-sla-t003",
    kind: "sla-risk",
    source: "SLA monitor",
    action: "reported a breach on",
    objectLabel: "Ticket #-003",
    detail: "Enterprise rollout is waiting on an ownership decision.",
    timestampLabel: "12m",
    dateGroup: "Today",
    destination: "/tickets/t-003",
    isRead: false,
  },
  {
    id: "notification-reply-inbox",
    kind: "customer-reply",
    source: "Lattice Cloud",
    action: "replied to",
    objectLabel: "your assigned conversation",
    detail: "We can share the activation cohort export today.",
    timestampLabel: "24m",
    dateGroup: "Today",
    destination: "/inbox",
    isRead: false,
  },
  {
    id: "notification-assignment-t002",
    kind: "assignment",
    source: "Annie Nguyen",
    action: "assigned you to",
    objectLabel: "Ticket #-002",
    detail: "Salesforce health sync escalation",
    timestampLabel: "42m",
    dateGroup: "Today",
    destination: "/tickets/t-002",
    isRead: false,
  },
  {
    id: "notification-automation",
    kind: "automation-failure",
    source: "Automation",
    action: "failed to run",
    objectLabel: "VIP escalation routing",
    detail: "The ticket remains unchanged. Review the rule configuration.",
    timestampLabel: "1h",
    dateGroup: "Today",
    destination: "/automation",
    isRead: false,
  },
  {
    id: "notification-reopened-t005",
    kind: "ticket-update",
    source: "Jason Support Lab",
    action: "reopened",
    objectLabel: "Ticket #-005",
    detail: "The customer added new billing context.",
    timestampLabel: "Yesterday",
    dateGroup: "Yesterday",
    destination: "/tickets/t-005",
    isRead: true,
  },
  {
    id: "notification-knowledge-review",
    kind: "knowledge-review",
    source: "Knowledge Base",
    action: "requested a review of",
    objectLabel: "Manage notification preferences",
    detail: "The article has new workspace policy guidance.",
    timestampLabel: "Yesterday",
    dateGroup: "Yesterday",
    destination: "/knowledge-base",
    isRead: true,
  },
]
