import type { InboxItem, InboxStatus, InboxView } from "@/lib/inbox/types"

const additionalConversations = [
  [
    "Noah Kim",
    "Meridian Cloud",
    "SSO certificate expires this week",
    "5h",
    5,
    "high",
    "t-001",
    "Our identity provider certificate expires on Friday. Can you confirm which certificate should be uploaded first so sign-in is not interrupted?",
  ],
  [
    "Amara Okafor",
    "Harbor Labs",
    "Sandbox data is not refreshing",
    "7h",
    6,
    "medium",
    "t-002",
    "The sandbox still shows yesterday's records even though our import completed this morning. Is the refresh queue delayed?",
  ],
  [
    "Liam Foster",
    "Northwind",
    "Billing export follow-up",
    "1d",
    7,
    "medium",
    "t-004",
    "The latest billing export is missing the adjustment rows we discussed. Could you check whether the corrected file is ready?",
  ],
  [
    "Mateo Ruiz",
    "Brightwell",
    "Need invoice tax details",
    "1d",
    9,
    "low",
    "t-005",
    "Could you send an invoice that separates the tax amount from the subscription total for our accounting team?",
  ],
  [
    "Olivia Park",
    "Lumen Systems",
    "Invite email was not received",
    "2d",
    10,
    "medium",
    "t-006",
    "I invited two colleagues yesterday, but neither received the welcome email. They checked spam and the addresses are correct.",
  ],
  [
    "Daniel Brooks",
    "Aperture",
    "Audit log export is missing rows",
    "2d",
    11,
    "high",
    "t-007",
    "Our audit log CSV jumps from Tuesday to Thursday. The entries are visible in the app but absent from the downloaded file.",
  ],
  [
    "Leila Hassan",
    "Atlas Works",
    "Role permissions do not match",
    "2d",
    12,
    "high",
    "t-009",
    "A viewer can edit one of our shared dashboards after the last role update. Please help us review the permission mapping.",
  ],
  [
    "Amina Rahman",
    "Folio",
    "Low activation in onboarding cohort",
    "3d",
    13,
    "low",
    "t-010",
    "Only a small part of our new cohort has completed setup. Do you have a way to identify where people are getting stuck?",
  ],
  [
    "Ben Carter",
    "Orbital",
    "Checkout integration question",
    "3d",
    14,
    "medium",
    "t-012",
    "We are connecting checkout events to our workspace. Which event should we use to distinguish an abandoned checkout from a failed payment?",
  ],
  [
    "Grace Lee",
    "Evergreen",
    "Data retention policy request",
    "3d",
    15,
    "low",
    "t-013",
    "Our compliance review needs the current retention window and deletion process for archived customer records.",
  ],
] as const

const additionalInboxItems: InboxItem[] = additionalConversations.map(
  ([
    contact,
    customer,
    subject,
    updatedAt,
    displayOrder,
    priority,
    ticketId,
    body,
  ]) => ({
    id: `inbox-${ticketId.slice(2)}`,
    ticketId,
    ticketNumber: `#TC-${ticketId.slice(2)}`,
    contact,
    customer,
    accountName: customer,
    subject,
    latestUpdate: subject,
    updatedAt,
    displayOrder,
    owner: "Jason Duong",
    status: "open",
    priority,
    slaState: "on-track",
    unread: false,
    mine: true,
    messages: [
      {
        id: `message-${ticketId}`,
        author: contact,
        role: "customer",
        sentAt: updatedAt,
        body,
      },
    ],
  })
)

export const inboxItems: InboxItem[] = [
  {
    id: "inbox-018",
    ticketId: "t-018",
    ticketNumber: "#TC-018",
    customer: "Acme",
    contact: "Maya Ortiz",
    displayOrder: 0,
    accountName: "Acme Inc.",
    subject: "Export failed after latest update",
    latestUpdate: "Export failed after latest update",
    updatedAt: "5m",
    owner: "Jason Duong",
    status: "open",
    priority: "urgent",
    slaState: "at-risk",
    slaLabel: "18m left",
    unread: true,
    mine: true,
    events: [
      {
        id: "e-018-created",
        title: "Ticket created",
        body: "Maya Ortiz opened the thread from Acme Inc. via Email.",
        time: "9:05 AM",
        position: "before",
      },
      {
        id: "e-018-priority",
        title: "Priority updated to Urgent",
        body: "Reporting is blocked for the customer’s operations team.",
        time: "10:02 AM",
        position: "after",
      },
      {
        id: "e-018-type",
        title: "Ticket type confirmed as Incident",
        body: "Export failures were reproduced across CSV and XLSX formats.",
        time: "10:09 AM",
        position: "after",
      },
    ],
    messages: [
      {
        id: "m-018-1",
        author: "Maya Ortiz",
        role: "customer",
        sentAt: "9:12 AM",
        body: "Our operations team started seeing export failures immediately after yesterday’s update. CSV and XLSX both stop before the download begins, and the issue is blocking today’s reporting.",
      },
      {
        id: "m-018-2",
        author: "Jason",
        role: "agent",
        sentAt: "9:18 AM",
        body: "Thanks for flagging this. I’ve reproduced the failure and am checking whether the latest export service change caused it. I’ll share a workaround or recovery timeline shortly.",
      },
      {
        id: "m-018-3",
        author: "Maya Ortiz",
        role: "customer",
        sentAt: "9:26 AM",
        body: "Thanks. We can provide request IDs if that helps. The reporting team needs an export before noon.",
      },
      {
        id: "m-018-4",
        author: "Jason",
        role: "agent",
        sentAt: "9:34 AM",
        body: "Please send one recent request ID. I’m also preparing a fallback export while engineering reviews the service.",
      },
    ],
  },
  {
    id: "inbox-003",
    ticketId: "t-003",
    ticketNumber: "#TC-003",
    customer: "Beta Health",
    contact: "Priya Shah",
    displayOrder: 2,
    accountName: "Beta Health",
    subject: "Access request still pending",
    latestUpdate: "Customer replied 2h ago",
    updatedAt: "2h",
    owner: "Jason Duong",
    status: "open",
    priority: "high",
    slaState: "on-track",
    slaLabel: "6h left",
    unread: true,
    mine: true,
    messages: [
      {
        id: "m-003-1",
        author: "Priya Shah",
        role: "customer",
        sentAt: "Today 8:40 AM",
        body: "Our workspace admin still cannot approve the access request. Is there another verification step?",
      },
    ],
  },
  {
    id: "inbox-008",
    ticketId: "t-008",
    ticketNumber: "#TC-008",
    customer: "NovaTech",
    contact: "Evan Cole",
    displayOrder: 3,
    accountName: "NovaTech Labs",
    subject: "Cannot log in after enabling SSO",
    latestUpdate: "Customer replied 4h ago",
    updatedAt: "4h",
    owner: "Jason Duong",
    status: "open",
    priority: "urgent",
    slaState: "breached",
    slaLabel: "Overdue 24m",
    unread: true,
    mine: true,
    messages: [
      {
        id: "m-008-1",
        author: "Evan Cole",
        role: "customer",
        sentAt: "Today 7:05 AM",
        body: "None of our admins can access the dashboard after enabling SSO this morning.",
      },
    ],
  },
  {
    id: "inbox-015",
    ticketId: "t-015",
    ticketNumber: "#TC-015",
    customer: "Global Retail",
    contact: "Lucas Bennett",
    displayOrder: 1,
    accountName: "Global Retail Group",
    subject: "Integration plan owner and timeline",
    latestUpdate: "Snooze ended 12m ago",
    updatedAt: "12m",
    owner: "Jason Duong",
    status: "open",
    priority: "medium",
    slaState: "on-track",
    slaLabel: "Tomorrow",
    unread: true,
    mine: true,
    returnedFromSnooze: true,
    messages: [
      {
        id: "m-015-1",
        author: "Lucas Bennett",
        role: "customer",
        sentAt: "Yesterday 3:20 PM",
        body: "Could we confirm the owner and timeline for phase two of the integration?",
      },
    ],
  },
  {
    id: "inbox-011",
    ticketId: "t-011",
    ticketNumber: "#TC-011",
    customer: "Summit Co",
    contact: "Chloe Nguyen",
    displayOrder: 8,
    accountName: "Summit Co",
    subject: "Question about user limits",
    latestUpdate: "Customer replied 1d ago",
    updatedAt: "1d",
    owner: "Jason Duong",
    status: "open",
    priority: "low",
    slaState: "on-track",
    slaLabel: "2d left",
    unread: false,
    mine: true,
    messages: [
      {
        id: "m-011-1",
        author: "Chloe Nguyen",
        role: "customer",
        sentAt: "Yesterday 11:34 AM",
        body: "Does the next plan tier increase both member seats and guest limits?",
      },
    ],
  },
  {
    id: "inbox-014",
    ticketId: "t-014",
    ticketNumber: "#TC-014",
    customer: "Northstar",
    contact: "Sofia Marin",
    displayOrder: 4,
    accountName: "Northstar Finance",
    subject: "Webhook deliveries are delayed",
    latestUpdate: "Webhook deliveries are delayed",
    updatedAt: "1d",
    owner: "Jason Duong",
    status: "open",
    priority: "medium",
    slaState: "on-track",
    unread: false,
    mine: true,
    messages: [
      {
        id: "m-014-1",
        author: "Sofia Marin",
        role: "customer",
        sentAt: "Yesterday 9:15 AM",
        body: "Webhook deliveries have been delayed since this morning. Can you confirm whether the queue is recovering?",
      },
    ],
  },
  ...additionalInboxItems,
  {
    id: "inbox-016",
    ticketId: "t-016",
    ticketNumber: "#TC-016",
    contact: "Nina Rao",
    customer: "Pinecrest",
    accountName: "Pinecrest Digital",
    subject: "Workspace access after team migration",
    latestUpdate: "New unassigned conversation",
    updatedAt: "18m",
    status: "unassigned",
    priority: "high",
    slaState: "at-risk",
    slaLabel: "42m left",
    unread: true,
    mine: false,
    messages: [
      {
        id: "m-016-1",
        author: "Nina Rao",
        role: "customer",
        sentAt: "9:48 AM",
        body: "Our team moved workspaces this morning and two admins can no longer access their accounts. Who can help us restore access?",
      },
    ],
  },
  {
    id: "inbox-017",
    ticketId: "t-017",
    ticketNumber: "#TC-017",
    contact: "Hugo Silva",
    customer: "Willow Finance",
    accountName: "Willow Finance",
    subject: "Confirm the billing period for export",
    latestUpdate: "Snoozed until tomorrow",
    updatedAt: "1d",
    owner: "Jason Duong",
    status: "snoozed",
    priority: "medium",
    slaState: "on-track",
    unread: false,
    mine: true,
    messages: [
      {
        id: "m-017-1",
        author: "Hugo Silva",
        role: "customer",
        sentAt: "Yesterday 2:20 PM",
        body: "We'll confirm which billing period we need tomorrow, then send you the export details.",
      },
    ],
  },
]

export const inboxStatusLabel: Record<InboxStatus, string> = {
  unassigned: "Unassigned",
  open: "Open",
  waiting: "Waiting",
  snoozed: "Snoozed",
  resolved: "Resolved",
}

export function isItemInInboxView(item: InboxItem, view: InboxView) {
  if (view === "mine") {
    return item.mine && ["open", "unassigned"].includes(item.status)
  }
  if (view === "unassigned") return item.status === "unassigned"
  if (view === "snoozed") return item.status === "snoozed"
  return ["open", "unassigned", "waiting"].includes(item.status)
}

export function getInboxViewCounts(items: InboxItem[]) {
  return {
    mine: items.filter((item) => isItemInInboxView(item, "mine")).length,
    unassigned: items.filter((item) => isItemInInboxView(item, "unassigned"))
      .length,
    "all-open": items.filter((item) => isItemInInboxView(item, "all-open"))
      .length,
    snoozed: items.filter((item) => isItemInInboxView(item, "snoozed")).length,
  }
}
